export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_USER = 'LOGOUT_USER';
export const CLOSE_SIGNUP_MODAL = 'CLOSE_SIGNUP_MODAL';
export const LOADING = 'LOADING';
export const FETCH_CUSTOMER_ORDERS = "FETCH_CUSTOMER_ORDERS";
export const FETCH_ORDER_DETAILS = "FETCH_ORDER_DETAILS";
export const PRODUCT_CATALOG = 'PRODUCT_CATALOG';
export const PRODUCT_SEARCH_INPUT = 'PRODUCT_SEARCH_INPUT';
export const CUSTOMER_DATA = 'CUSTOMER_DATA';

export const SELLER_ALL_PRODUCTS = 'SELLER_ALL_PRODUCTS';
export const ADD_NEW_PRODUCT = "ADD_NEW_PRODUCT";
export const ADD_NEW_PRODUCT_FAILURE = "ADD_NEW_PRODUCT_FAILURE";
export const SHOW_ADD_PRODUCT = "SHOW_ADD_PRODUCT";
export const SELLER_PRODUCT_CATALOG = "SELLER_PRODUCT_CATALOG";
export const SHOW_EDIT_PRODUCT = "SHOW_EDIT_PRODUCT";
export const EDIT_PRODUCT = "EDIT_PRODUCT"

export const PRODUCT_DETAILS = "PRODUCT_DETAILS"

